notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

addons:
 apt:
  packages:
   - build-essential
   - autoconf
   - bsdtar
   - time
   - curl
   - libcurl4-openssl-dev
   - nettle-dev
   - zlib1g-dev
   - libncurses5-dev
   - libpstreams-dev
   - unzip
   - libpng12-dev
   - libexpat1-dev

env:
 - CC=gcc

language:
 - perl

perl:
 - "5.22"
 - "5.14"

install: true

script:
 - gcc --version
 - perl --version
# - curl -L https://github.com/ICGC-TCGA-PanCancer/PCAP-core/archive/feature/adapter-trim.zip > master.zip
# - unzip master.zip
# - bash -c 'cd PCAP-core-feature-adapter-trim; ./setup.sh ~/wtsi-cgp'
