language:
 - perl

perl:
 - "5.24"
 - "5.22"
 - "5.20"
 - "5.18"
 - "5.16"
 - "5.14"

# blocklist
branches:
  except:/^feature.*/

install: true

script:
 - perl bin/test.pl



# comment to check branch exclusion worked
