notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

sudo: required
dist: trusty

install: true

language:
 - perl

perl:
 - "5.16"

before_install:
 - sudo apt-get install -yq build-essential
 - sudo apt-get install -yq autoconf
 - sudo apt-get install -yq bsdtar time curl
 - sudo apt-get install -yq libcurl4-openssl-dev
 - sudo apt-get install -yq nettle-dev
 - sudo apt-get install -yq zlib1g-dev
 - sudo apt-get install -yq libncurses5-dev
 - sudo apt-get install -yq libpstreams-dev
 - sudo apt-get install -yq unzip
 - sudo apt-get install -yq libpng12-dev
 - sudo apt-get install -yq libexpat1-dev

script:
 - export CPU=`grep -c ^processor /proc/cpuinfo`
 - curl -L http://hgdownload.cse.ucsc.edu/admin/jksrc.zip > kentsrc.zip
 - unzip -q kentsrc.zip
 - perl -pi -e 's/(\s+CFLAGS=)$/${1}-fPIC/' kent/src/inc/common.mk
 - cd kent/src/lib
 - export MACHTYPE=i686    # for a 64-bit system
 - make -j$CPU
 - cd ../
 - export KENT_SRC=`pwd`
 - cd ../
 - cpanm -v --no-interactive --mirror http://cpan.metacpan.org -l ~/wtsi-cgp Bio::DB::BigFile
