notifications:
  slack: wtsi-cgpit:vtT8FxSRsOnHblGjzu6YTfvN
  email: false

env:
 - CC=gcc

addons:
 apt:
  packages:
   - build-essential
   - autoconf
   - bsdtar
   - time
   - curl
   - libcurl4-openssl-dev
   - nettle-dev
   - zlib1g-dev
   - libncurses5-dev
   - libpstreams-dev
   - unzip
   - libpng12-dev
   - libexpat1-dev

language: c

#perl:
# - "5.14"

install: true

script:
 - gcc --version
 - perl --version
 - curl -L https://github.com/ICGC-TCGA-PanCancer/PCAP-core/archive/feature/adapter-trim.zip > master.zip
 - unzip master.zip
 - bash -c 'cd PCAP-core-feature-adapter-trim; ./setup.sh ~/wtsi-cgp'
