notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

sudo: false

services:
  - docker


script:
  - cat /proc/cpuinfo | egrep "^processor" | wc -l
  - mkdir test
  - echo "FROM  alpine:3.7" > test/Dockerfile
  - echo "RUN apk update" >> test/Dockerfile
  - echo "RUN apk upgrade" >> test/Dockerfile
  - echo "RUN apk add bash" >> test/Dockerfile
  - echo 'CMD ["/bin/bash"]' >> test/Dockerfile
  - cd test
  - docker build -t wibble .
  - docker run wibble 'cat /proc/cpuinfo | egrep "^processor" | wc -l'

#  - curl -sSL https://github.com/cancerit/dockstore-cgpmap/archive/feature/mmqc_metaRg.tar.gz | tar -zx
#  - cd dockstore-cgpmap-feature-mmqc_metaRg
#  - docker bash
  -
